// @generated
// This file is autogenerated, do not edit manually

module Root = {
  module Route = Route__Root_route

  module Dashboard = {
    module Route = Route__Root__Dashboard_route

  }
  module UserProfile = {
    module Route = Route__Root__UserProfile_route

  }
}
module FourOhFour = {
  module Route = Route__FourOhFour_route

}